remove failure

diff --git a/.github/workflows/dbcp-flow.yml b/.github/workflows/dbcp-flow.yml
--- a/.github/workflows/dbcp-flow.yml
+++ b/.github/workflows/dbcp-flow.yml
@@ -21,9 +21,9 @@ jobs:
         run: |
           echo "Archiving data..."
 
-      # add a step that fails
-      - name: Fail
-        run: exit 1
+      # # add a step that fails
+      # - name: Fail
+      #   run: exit 1
 
   matrix_prep:
     needs: archive # Ensure archive job finishes first
