add fail

diff --git a/.github/workflows/dbcp-flow.yml b/.github/workflows/dbcp-flow.yml
--- a/.github/workflows/dbcp-flow.yml
+++ b/.github/workflows/dbcp-flow.yml
@@ -48,10 +48,14 @@ jobs:
       - name: echo matrix
         run: echo ${{ steps.set-matrix.outputs.matrix }}
 
+      # add a step that fails
+      - name: Fail
+        run: exit 1
+
   etl:
     needs: matrix_prep # Ensure archive job finishes first
     runs-on: ubuntu-latest
-    if: ${{ needs.matrix_prep.result == 'success' }}
+    if: ${{ always() && needs.matrix_prep.result == 'success' }}
     strategy:
       matrix: ${{ fromJSON(needs.matrix_prep.outputs.matrix) }}
     steps:
